### ISSUE TITLE
set ACL parameters when uploading

### ISSUE THREAD

**Issue by Gorbus** [Lepozepo/s3-uploader#14]
Hi, great package, very useful.

I could manage to upload file but somehow I can't read them yet. I'd like to set up the ACL parameters to public-read so that everyone could have access to the file, where shall I change this?I tried to do the following in s3Up.signUpload function: 

```
s3Up.signUpload({
key,
ACL: "public-read"
})
```

but it didn't succeed.

Also is there a more secured way to control who has access to the pictures (getting signedUrl to download for example, in Mteor to at least check if user is authenticated before accessing a picture, etc... ?

Thanks a lot

**Comment by Lepozepo** [comment]
@Gorbus you can set `acl` under the `fields` object. So `s3Up.signUpload({ fields: { acl: 'public-read' }})`. If you don't want to have to set the `acl` parameter you can allow everyone read access to your bucket by reconfiguring your bucket and setting public read access under your bucket policy, otherwise this should work as well. Let me know if it doesn't though ^_^.

As for more controlled way to who has access to what you're uploading to S3, there are 2 ways. You can set host permissions in your bucket policy OR you can create signed get requests (this is a feature I'll be making available more easily through a separate PR though so you'll need to use aws-sdk directly for now via `s3Up.client`)
